article_index:
    path:     /admin/
    defaults: { _controller: "sil16VitrineBundle:Article:index" }
    methods:  GET

article_show:
    path:     /admin/{id}/show
    defaults: { _controller: "sil16VitrineBundle:Article:show" }
    methods:  GET

article_new:
    path:     /admin/new
    defaults: { _controller: "sil16VitrineBundle:Article:new" }
    methods:  [GET, POST]

article_edit:
    path:     /admin/{id}/edit
    defaults: { _controller: "sil16VitrineBundle:Article:edit" }
    methods:  [GET, POST]

article_delete:
    path:     /admin/{id}/delete
    defaults: { _controller: "sil16VitrineBundle:Article:delete" }
    methods:  [GET, DELETE]
