category_index:
    path:     /admin/
    defaults: { _controller: "sil16VitrineBundle:Category:index" }
    methods:  GET

category_show:
    path:     /admin/{id}/show
    defaults: { _controller: "sil16VitrineBundle:Category:show" }
    methods:  GET

category_new:
    path:     /admin/new
    defaults: { _controller: "sil16VitrineBundle:Category:new" }
    methods:  [GET, POST]

category_edit:
    path:     /admin/{id}/edit
    defaults: { _controller: "sil16VitrineBundle:Category:edit" }
    methods:  [GET, POST]

category_delete:
    path:     /admin/{id}/delete
    defaults: { _controller: "sil16VitrineBundle:Category:delete" }
    methods:  [GET, POST, DELETE]
