client_index:
    path:     /admin/
    defaults: { _controller: "sil16VitrineBundle:Client:index" }
    methods:  GET

client_show:
    path:     /admin/{id}/show
    defaults: { _controller: "sil16VitrineBundle:Client:show" }
    methods:  GET

client_new:
    path:     /new
    defaults: { _controller: "sil16VitrineBundle:Client:new" }
    methods:  [GET, POST]

client_edit:
    path:     /admin/{id}/edit
    defaults: { _controller: "sil16VitrineBundle:Client:edit" }
    methods:  [GET, POST]

client_delete:
    path:     /admin/{id}/delete
    defaults: { _controller: "sil16VitrineBundle:Client:delete" }
    methods:  DELETE

client_profil:
    path:     /{id}/profil
    defaults: { _controller: "sil16VitrineBundle:Client:profil" }
    methods:  [GET, POST]

client_password:
    path:     /{id}/password
    defaults: { _controller: "sil16VitrineBundle:Client:password" }
    methods:  [GET, POST]