commande_index:
    path:     /admin/{client_id}
    defaults: { _controller: "sil16VitrineBundle:Commande:index", client_id:null }
    methods:  GET

commande_show:
    path:     /admin/{id}/show
    defaults: { _controller: "sil16VitrineBundle:Commande:show" }
    methods:  GET

commande_new:
    path:     /admin/new
    defaults: { _controller: "sil16VitrineBundle:Commande:new" }
    methods:  [GET, POST]

commande_edit:
    path:     /admin/{id}/edit
    defaults: { _controller: "sil16VitrineBundle:Commande:edit" }
    methods:  [GET, POST]

commande_delete:
    path:     /admin/{id}/delete
    defaults: { _controller: "sil16VitrineBundle:Commande:delete" }
    methods:  DELETE

commande_indexClient:
    path:     /{client_id}/listCommande
    defaults: { _controller: "sil16VitrineBundle:Commande:indexClient", client_id:-1 }
    methods:  GET