commande_index:
    path:     /admin/
    defaults: { _controller: "sil16VitrineBundle:Commande:index"}
    methods:  GET

commande_show:
    path:     /admin/{id}/show
    defaults: { _controller: "sil16VitrineBundle:Commande:show" }
    methods:  GET

commande_new:
    path:     /admin/new
    defaults: { _controller: "sil16VitrineBundle:Commande:new" }
    methods:  [GET, POST]

commande_edit:
    path:     /admin/{id}/edit
    defaults: { _controller: "sil16VitrineBundle:Commande:edit" }
    methods:  [GET, POST]

commande_delete:
    path:     /admin/{id}/delete
    defaults: { _controller: "sil16VitrineBundle:Commande:delete" }
    methods:  DELETE

commande_mesCommandes:
    path:     /user/mesCommandes
    defaults: { _controller: "sil16VitrineBundle:Commande:mesCommandes"}
    methods:  GET