# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
#        in_memory:
#            memory: ~
        utilisateurs:
            entity: { class: sil16VitrineBundle:Client, property: mail }

    firewalls:
        vitrine_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /
    encoders:
      sil16\VitrineBundle\Entity\Client:
        algorithm: bcrypt
        cost: 12

    role_hierarchy:
      ROLE_ADMIN: ROLE_USER

    access_control:
      - { path: admin, roles: ROLE_ADMIN }
#      - { path: ^/, roles: ROLE_USER }