sil16_vitrine_homepage:
    path:     /
    defaults: { _controller: sil16VitrineBundle:Default:index}

accueil:
    path:     /accueil/{name}
    defaults: { _controller: sil16VitrineBundle:Default:index, name:visiteur }

mentions:
    path:     /mentions
    defaults: { _controller: sil16VitrineBundle:Default:mentions }

catalogue:
    path:     /catalogue
    defaults: { _controller: sil16VitrineBundle:Default:catalogue }

catalogueWithCategory:
    path:     /catalogue/{category_id}
    defaults: { _controller: sil16VitrineBundle:Default:articlesByCategory }

articlesLesPlusVendu:
    path:     /articlesLesPlusVendu
    defaults: { _controller: sil16VitrineBundle:Default:articlesLesPlusVendu }

#Actions relatif au panier
contenuPanier:
    path:     /panier
    defaults: { _controller: sil16VitrineBundle:Default:contenuPanier }

addArticle:
    path:     /addArticle/{article_id}
    defaults: { _controller: sil16VitrineBundle:Default:addArticle }

addArticleFromCategory:
    path:     /addArticleFromCategory/{article_id}
    defaults: { _controller: sil16VitrineBundle:Default:addArticleFromCategory }

removeArticleFromPanier:
    path:     /removeArticleFromPanier/{article_id}
    defaults: { _controller: sil16VitrineBundle:Default:removeArticleFromPanier }

removePanierContent:
    path:     /removePanierContent
    defaults: { _controller: sil16VitrineBundle:Default:removePanierContent }

panierInformationAction:
    path:     /panierInformation
    defaults: { _controller: sil16VitrineBundle:Default:panierInformation }