sil16_vitrine_category:
    resource: "@sil16VitrineBundle/Resources/config/routing/category.yml"
    prefix:   /category

sil16_vitrine_article:
    resource: "@sil16VitrineBundle/Resources/config/routing/article.yml"
    prefix:   /article

sil16_vitrine_client:
    resource: "@sil16VitrineBundle/Resources/config/routing/client.yml"
    prefix:   /client

sil16_vitrine_commande:
    resource: "@sil16VitrineBundle/Resources/config/routing/commande.yml"
    prefix:   /commande


sil16_vitrine_homepage:
    path:     /
    defaults: { _controller: sil16VitrineBundle:Default:index}

accueil:
    path:     /accueil/{name}
    defaults: { _controller: sil16VitrineBundle:Default:index, name:visiteur }

mentions:
    path:     /mentions
    defaults: { _controller: sil16VitrineBundle:Default:mentions }

catalogue:
    path:     /catalogue
    defaults: { _controller: sil16VitrineBundle:Default:catalogue }

catalogueWithCategory:
    path:     /catalogue/{category_id}
    defaults: { _controller: sil16VitrineBundle:Default:articlesByCategory }

articlesLesPlusVendu:
    path:     /articlesLesPlusVendu
    defaults: { _controller: sil16VitrineBundle:Default:articlesLesPlusVendu }

updateNbTopArticles:
    path:     /updateNbTopArticles
    defaults: { _controller: sil16VitrineBundle:Default:updateNbTopArticles }

#Actions relatif au panier
contenuPanier:
    path:     /panier
    defaults: { _controller: sil16VitrineBundle:Panier:contenuPanier }

addArticle:
    path:     /addArticle/{article_id}
    defaults: { _controller: sil16VitrineBundle:Panier:addArticle }

addArticleFromCategory:
    path:     /addArticleFromCategory/{article_id}
    defaults: { _controller: sil16VitrineBundle:Panier:addArticleFromCategory }

removeArticleFromPanier:
    path:     /removeArticleFromPanier/{article_id}
    defaults: { _controller: sil16VitrineBundle:Panier:removeArticleFromPanier }

removePanierContent:
    path:     /removePanierContent
    defaults: { _controller: sil16VitrineBundle:Panier:removePanierContent }

panierInformation:
    path:     /panierInformation
    defaults: { _controller: sil16VitrineBundle:Panier:panierInformation }

validerPanier:
    path:     /validerPanier
    defaults: { _controller: sil16VitrineBundle:Panier:validerPanier }