# silXX/VitrineBundle/Resources/config/validation.yml
sil16\VitrineBundle\Entity\Client:
  properties:
  nom:
    - NotBlank: ~
    - Type: \TextType
  mail:
    - NotBlank: ~
    - Type: \Email
  password:
    - NotBlank: ~
    - Type: \UserPassword
#  mail:
#    - NotBlank: ~
#    - Type: \email
#  password:
#    - NotBlank: ~
#    - Type: \PasswordType

#  mail:
#    - NotBlank: ~
#    - Type: \EmailType