sil16\VitrineBundle\Entity\Article:
  type: entity
  repositoryClass: sil16\VitrineBundle\Entity\ArticleRepository
  table: article
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    libelle:
      type: string
    price:
      type: decimal
      scale: 2
    stock:
      type: integer
    image_url:
      type: string
  manyToOne:
    category:
      targetEntity: Category
      inversedBy: articles
      joinColumn:
        name: category_id
        referencedColumnName: id