sil16\VitrineBundle\Entity\LigneDeCommande:
  type: entity
  table: ligneDeCommande
  id:
    commande:
      associationKey: true
    article:
      associationKey: true
  fields:
    quantite:
      type: string
    price:
      type: decimal
      scale: 2
  manyToOne:
    commande:
      targetEntity: Commande
      inversedBy: lignesDeCommandes
      joinColumn:
        name: commande_id
        referencedColumnName: id
    article:
      targetEntity: Article
      joinColumn:
        name: article_id
        referencedColumnName: id